name: amaterasutrip
description: "Amaterasu Trip - Japan Travel Planner"
publish_to: 'none'
version: 1.3.1+3
environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State management
  flutter_riverpod: ^3.3.2
  # Navigation
  go_router: ^17.3.0
  # Firebase
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  # Authentication
  google_sign_in: ^6.2.1
  # Local storage
  shared_preferences: ^2.5.5
  cloud_functions: ^6.4.0
  url_launcher: ^6.3.2
  firebase_storage: ^13.6.0
  image_picker: ^1.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/amaterasu_logo.png
    - assets/icons/discord.png
    - assets/icons/google.png
    - assets/branding/
    - assets/images/profile/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/amaterasu_logo.png"