// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHtqVjToyZbVqbUrwB6pTKtZWYhY5hGk0',
    appId: '1:189662926755:web:e323ea20846118c900ac16',
    messagingSenderId: '189662926755',
    projectId: 'amaterasutrip',
    authDomain: 'amaterasutrip.firebaseapp.com',
    storageBucket: 'amaterasutrip.firebasestorage.app',
    measurementId: 'G-QRK7VFHE5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzTuGb6KKlJzyKxhZ1Y1VXWThO1It8aw',
    appId: '1:189662926755:android:e011004f5976e7b000ac16',
    messagingSenderId: '189662926755',
    projectId: 'amaterasutrip',
    storageBucket: 'amaterasutrip.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLMDyMR9sDJ1dJNoynY6DsSrK9beRDmhQ',
    appId: '1:189662926755:ios:aeee6644bc25f4f500ac16',
    messagingSenderId: '189662926755',
    projectId: 'amaterasutrip',
    storageBucket: 'amaterasutrip.firebasestorage.app',
    iosClientId: '189662926755-og7mp573rpcepos1hsho6bl0jmtdi9uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.amaterasutrip',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLMDyMR9sDJ1dJNoynY6DsSrK9beRDmhQ',
    appId: '1:189662926755:ios:aeee6644bc25f4f500ac16',
    messagingSenderId: '189662926755',
    projectId: 'amaterasutrip',
    storageBucket: 'amaterasutrip.firebasestorage.app',
    iosClientId: '189662926755-og7mp573rpcepos1hsho6bl0jmtdi9uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.amaterasutrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHtqVjToyZbVqbUrwB6pTKtZWYhY5hGk0',
    appId: '1:189662926755:web:adc6438ea41d8a1300ac16',
    messagingSenderId: '189662926755',
    projectId: 'amaterasutrip',
    authDomain: 'amaterasutrip.firebaseapp.com',
    storageBucket: 'amaterasutrip.firebasestorage.app',
    measurementId: 'G-9KWGLD0LQP',
  );
}
